theme: jekyll-theme-slate
title: This is the personal homepage od Michael Schiltz
description: What you will find here are links to projects, publications, and repositories related to the former. Expect some delay in reporting!
