theme: jekyll-theme-slate
title: The personal homepage of Michael Schiltz, financial historian and intermittent archivist
description: What you will find here are links to projects, publications, and repositories related to the former. Expect some delay in reporting!
plugins:
  - jemoji
url: "https://michaelschiltz.github.io/"
markdown: kramdown
